# Generated by Django 4.2.7 on 2026-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(help_text='Image displayed on desktop and tablet devices (1920x600px recommended)', upload_to='hero_banners/desktop/')),
                ('mobile_image', models.ImageField(help_text='Image displayed on mobile devices (540x800px recommended)', upload_to='hero_banners/mobile/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the slide appears. Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this slide without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order'],
            },
        ),
    ]
