# Generated by Django 4.2.7 on 2026-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='hero_url',
            field=models.URLField(blank=True, help_text='Destination URL when user clicks the hero slide. Leave blank to use Products page.', max_length=500, null=True),
        ),
    ]
