# Generated by Django 5.2.17 on 2026-08-13 10:03

import ComfyCuteApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0007_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Announcement text to display in the announcement bar', max_length=255)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-bell', help_text='FontAwesome icon class (e.g., "fa-solid fa-truck-fast", leave blank for no icon)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order - lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable announcement without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ComfyCuteApp.models.CustomUserManager()),
            ],
        ),
    ]
