# Generated by Django 5.2.17 on 2026-08-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0008_announcement_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Baby, Girl, Boy, Women)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., baby, girl, boy, women)', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Category image/icon for display in navigation', null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subcategory name (e.g., Baby Boy, Cotton Churidar)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., baby-boy, cotton-churidar)', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Subcategory image for display in navigation', null=True, upload_to='subcategories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ComfyCuteApp.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
