# Generated by Django 5.2.17 on 2026-08-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0009_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name', max_length=150)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Collection cover image', null=True, upload_to='collections/')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable collection without deleting it')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order - lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Color name (e.g., Red, Blue, Pink)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fabric name (e.g., Cotton, Linen, Silk)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size name (e.g., S, M, L, 0-3 Months)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order - lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name (e.g., Girls Cotton T-Shirt)', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('main_image', models.ImageField(help_text='Main product listing/card image', upload_to='products/main/')),
                ('short_description', models.TextField(blank=True, help_text='Brief product description for product cards', null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original/marked price (optional)', max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Current selling price (required)', max_digits=10)),
                ('full_description', models.TextField(blank=True, help_text='Detailed product description', null=True)),
                ('fabric_and_care', models.TextField(blank=True, help_text='Fabric information and care instructions', null=True)),
                ('shipping_and_returns', models.TextField(blank=True, help_text='Shipping and returns information', null=True)),
                ('manufactured_by', models.TextField(blank=True, help_text='Manufacturing information', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable product without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category (required)', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ComfyCuteApp.category')),
                ('collections', models.ManyToManyField(blank=True, help_text='Collections this product belongs to', related_name='products', to='ComfyCuteApp.collection')),
                ('fabric', models.ForeignKey(help_text='Fabric/material (required)', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ComfyCuteApp.fabric')),
                ('subcategory', models.ForeignKey(help_text='Product subcategory (required)', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ComfyCuteApp.subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default variant for product detail page')),
                ('old_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override product old price for this variant (optional)', max_digits=10, null=True)),
                ('selling_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override product selling price for this variant (optional)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable variant without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(help_text='Variant color', on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='ComfyCuteApp.color')),
                ('product', models.ForeignKey(help_text='Parent product', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ComfyCuteApp.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'color'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Variant image (e.g., front, back, side view)', upload_to='products/variants/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order - lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(help_text='Variant these images belong to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ComfyCuteApp.productvariant')),
            ],
            options={
                'verbose_name': 'Product Variant Image',
                'verbose_name_plural': 'Product Variant Images',
                'ordering': ['variant', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='VariantSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.ForeignKey(help_text='Size', on_delete=django.db.models.deletion.PROTECT, related_name='variant_stocks', to='ComfyCuteApp.size')),
                ('variant', models.ForeignKey(help_text='Product variant', on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='ComfyCuteApp.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Size Stock',
                'verbose_name_plural': 'Variant Size Stocks',
                'ordering': ['variant', 'size'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'size'), name='unique_variant_size')],
            },
        ),
    ]
