# Generated by Django 5.2.17 on 2026-08-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0010_collection_color_fabric_size_product_productvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
    ]
