# Generated by Django 5.2.17 on 2026-08-17 07:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0011_remove_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric_and_care',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Fabric information and care instructions', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_by',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Manufacturing information', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_and_returns',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Shipping and returns information', null=True),
        ),
    ]
