# Generated by Django 5.2.17 on 2026-08-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0012_alter_product_fabric_and_care_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier (e.g., baby-boy, cotton-churidar)', max_length=100, unique=True),
        ),
    ]
