# Generated by Django 5.2.17 on 2026-08-18 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0013_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users (NULL for authenticated users)', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product in wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='ComfyCuteApp.product')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (NULL for anonymous users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product_wishlist'), models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'product'), name='unique_session_product_wishlist')],
            },
        ),
    ]
