# Generated by Django 5.2.17 on 2026-08-20 05:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0016_cart_cartitem_cart_unique_user_active_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users (NULL for authenticated users)', max_length=40, null=True)),
                ('order_number', models.CharField(help_text='Unique order number for customer reference (e.g., ORD-20240101-001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current order fulfillment status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Order subtotal (sum of all item totals)', max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, help_text='Shipping charge (1-3 items: ₹40, 4+ items: ₹0)', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Applied discount amount (optional)', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Applicable tax amount (optional)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final total amount to be paid (subtotal + shipping + tax - discount)', max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay order ID generated during payment initialization', max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID returned after successful payment', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (NULL for anonymous sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity purchased', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of order creation (includes variant overrides)', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (unit_price × quantity)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ComfyCuteApp.order')),
                ('product', models.ForeignKey(help_text='Product in order (protected to maintain order history)', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ComfyCuteApp.product')),
                ('size', models.ForeignKey(help_text='Selected size at time of purchase', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ComfyCuteApp.size')),
                ('variant', models.ForeignKey(help_text='Product variant (color) at time of purchase', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ComfyCuteApp.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session_id__isnull', True), ('user__isnull', False)), models.Q(('session_id__isnull', False), ('user__isnull', True)), _connector='OR'), name='order_must_have_owner'),
        ),
    ]
