# Generated by Django 5.2.17 on 2026-08-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0017_order_orderitem_order_order_must_have_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='', help_text='Street address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_2',
            field=models.TextField(blank=True, help_text='Apartment, suite, etc. (optional)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', help_text='Customer email address', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', help_text='Customer first name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', help_text='Customer last name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', help_text='Customer phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', help_text='PIN code / Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', help_text='State', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final total amount to be paid (subtotal + shipping_charge)', max_digits=10),
        ),
    ]
