# Generated by Django 5.2.17 on 2026-08-20 10:41

from django.db import migrations, models
import secrets


def populate_invoice_tokens(apps, schema_editor):
    """Populate invoice_token for all existing orders."""
    Order = apps.get_model('ComfyCuteApp', 'Order')

    for order in Order.objects.filter(invoice_token__isnull=True):
        # Generate a cryptographically secure random token
        order.invoice_token = secrets.token_urlsafe(32)
        order.save(update_fields=['invoice_token'])


def reverse_populate_invoice_tokens(apps, schema_editor):
    """Reverse: clear invoice tokens (optional)."""
    Order = apps.get_model('ComfyCuteApp', 'Order')
    Order.objects.all().update(invoice_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ComfyCuteApp', '0018_remove_order_discount_remove_order_tax_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure random token for public invoice download (no authentication required)', max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_invoice_tokens, reverse_populate_invoice_tokens),
    ]
