from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
import threading
import logging
from .models import HeroBanner, ContactSubmission, Testimonial
from .forms import ContactSubmissionForm, RegistrationForm, EmailAuthenticationForm

logger = logging.getLogger(__name__)

def home(request):
    hero_banners = HeroBanner.objects.filter(is_active=True).order_by('order')
    testimonials = Testimonial.objects.filter(is_active=True)
    context = {
        'hero_banners': hero_banners,
        'testimonials': testimonials,
    }
    return render(request, 'index.html', context)

def products(request):
    return render(request, 'products.html')

def product_detail(request):
    return render(request, 'product-detail.html')

def send_contact_notification_email(contact_submission):
    """
    Send an email notification to the admin when a contact form is submitted.
    Runs in a background thread to avoid blocking the response.
    """
    try:
        subject = f"New Contact Form Submission - {contact_submission.get_subject_display()}"

        # Create email context
        context = {
            'first_name': contact_submission.first_name,
            'last_name': contact_submission.last_name,
            'email': contact_submission.email,
            'phone': contact_submission.phone or 'Not provided',
            'subject': contact_submission.get_subject_display(),
            'message': contact_submission.message,
            'submitted_at': contact_submission.created_at.strftime('%Y-%m-%d %H:%M:%S'),
        }

        # Render email template
        html_message = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                .header {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
                .header h2 {{ margin: 0; color: #333; }}
                .content {{ margin-bottom: 20px; }}
                .field {{ margin-bottom: 15px; }}
                .label {{ font-weight: bold; color: #555; }}
                .value {{ margin-top: 5px; color: #333; }}
                .message-box {{ background-color: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; border-radius: 3px; }}
                .footer {{ color: #999; font-size: 12px; margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h2>📬 New Contact Form Submission</h2>
                </div>

                <div class="content">
                    <div class="field">
                        <div class="label">Name:</div>
                        <div class="value">{context['first_name']} {context['last_name']}</div>
                    </div>

                    <div class="field">
                        <div class="label">Email:</div>
                        <div class="value"><a href="mailto:{context['email']}">{context['email']}</a></div>
                    </div>

                    <div class="field">
                        <div class="label">Phone:</div>
                        <div class="value">{context['phone']}</div>
                    </div>

                    <div class="field">
                        <div class="label">Subject:</div>
                        <div class="value">{context['subject']}</div>
                    </div>

                    <div class="field">
                        <div class="label">Message:</div>
                        <div class="message-box">{context['message']}</div>
                    </div>

                    <div class="field">
                        <div class="label">Submitted At:</div>
                        <div class="value">{context['submitted_at']}</div>
                    </div>
                </div>

                <div class="footer">
                    <p>This email was generated by the COMFY CUTE Contact Form system.</p>
                </div>
            </div>
        </body>
        </html>
        """

        send_mail(
            subject=subject,
            message='',  # Plain text fallback
            html_message=html_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.DEFAULT_FROM_EMAIL],
            fail_silently=False,
        )

        logger.info(f"Contact notification email sent for submission from {contact_submission.email}")
    except Exception as e:
        logger.error(f"Failed to send contact notification email: {str(e)}")


@require_http_methods(["GET", "POST"])
def contact(request):
    """
    Handle contact form requests.
    GET: Render the contact page with an empty form.
    POST: Process the form submission and send email.
    """
    if request.method == 'POST':
        # Handle AJAX form submission
        form = ContactSubmissionForm(request.POST)

        if form.is_valid():
            # Save the contact submission
            contact_submission = form.save()

            # Send email notification in background thread
            email_thread = threading.Thread(
                target=send_contact_notification_email,
                args=(contact_submission,),
                daemon=True
            )
            email_thread.start()

            # Return JSON response for AJAX
            return JsonResponse({
                'success': True,
                'message': 'Thank you for your message! We\'ll get back to you within 24 hours.',
                'submission_id': contact_submission.id,
            })
        else:
            # Return validation errors as JSON
            errors = {}
            for field, error_list in form.errors.items():
                errors[field] = error_list[0] if error_list else 'Invalid input'

            return JsonResponse({
                'success': False,
                'message': 'Please correct the errors below.',
                'errors': errors,
            }, status=400)

    # GET request: render the contact form
    form = ContactSubmissionForm()
    return render(request, 'contact.html', {'form': form})

def about_us(request):
    return render(request, 'about-us.html')

def wishlist(request):
    return render(request, 'wishlist.html')

def login(request):
    return render(request, 'login.html')

def track_order(request):
    return render(request, 'track-order.html')

def privacy_policy(request):
    return render(request, 'privacy-policy.html')

def terms_of_service(request):
    return render(request, 'terms-of-service.html')

def refund_policy(request):
    return render(request, 'refund-policy.html')

def shipping_policy(request):
    return render(request, 'shipping-policy.html')

def return_exchange(request):
    return render(request, 'return-exchange.html')



def checkout(request):
    """
    Checkout page view.
    Displays the checkout form where users can enter their billing and shipping information.
    Cart data is handled client-side via JavaScript and localStorage.
    """
    return render(request, 'checkout.html')


# ==========================================
# AUTHENTICATION VIEWS
# ==========================================

@require_http_methods(["GET", "POST"])
def register(request):
    """
    User registration view.
    POST: Process registration form and create account
    """
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Auto-login user after registration
            auth_login(request, user)
            return redirect('ComfyCuteApp:home')
        # Registration failed - show errors in register form and keep it active
        login_form = EmailAuthenticationForm()
        context = {'login_form': login_form, 'register_form': form, 'register_active': True}
        return render(request, 'login.html', context)

    # GET request - show both forms
    login_form = EmailAuthenticationForm()
    register_form = RegistrationForm()
    context = {'login_form': login_form, 'register_form': register_form}
    return render(request, 'login.html', context)


@require_http_methods(["GET", "POST"])
def login_view(request):
    """
    User login view.
    GET: Display login page with login and register forms
    POST: Process login form (email + password)
    """
    if request.user.is_authenticated:
        return redirect('ComfyCuteApp:home')

    if request.method == 'POST':
        login_form = EmailAuthenticationForm(request=request, data=request.POST)
        if login_form.is_valid():
            email = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(request, username=email, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('ComfyCuteApp:home')
        # Login failed - show errors in login form and keep it active
        register_form = RegistrationForm()
        context = {'login_form': login_form, 'register_form': register_form, 'login_active': True}
        return render(request, 'login.html', context)

    # GET request - show both forms
    login_form = EmailAuthenticationForm()
    register_form = RegistrationForm()
    context = {'login_form': login_form, 'register_form': register_form}
    return render(request, 'login.html', context)


@require_http_methods(["GET"])
def logout_view(request):
    """
    User logout view.
    Logs out the user and redirects to home.
    """
    auth_logout(request)
    return redirect('ComfyCuteApp:home')
